// Generated by CoffeeScript 1.6.1
(function() {
  var Addme, Facebook,
    _this = this;

  Addme = (function() {

    function Addme() {
      var isClicked,
        _this = this;
      isClicked = false;
      setInterval(function() {
        var el;
        el = document.querySelector("center > a > div.btn3");
        if (el) {
          if (!isClicked) {
            isClicked = true;
            return setTimeout(function() {
              return el.click();
            }, 1000);
          }
        } else {
          return isClicked = false;
        }
      }, 250);
    }

    return Addme;

  })();

  Facebook = (function() {

    function Facebook() {
      var _this = this;
      setTimeout(function() {
        jQuery("#timelineHeadlineLikeButton input[type=submit], sharerDialogButtons").click();
        jQuery("#sharerDialogButtons input[type=submit]").click();
        jQuery("#pagelet_escape_hatch input[type=submit]").click();
        jQuery(".UIActionLinks.UIActionLinks_bottom > a").click();
        jQuery(".PageLikeButton.uiButton.uiButtonOverlay.uiButtonLarge a").click();
        return setTimeout(function() {
          return window.close();
        }, 2000);
      }, 4000);
    }

    return Facebook;

  })();

  jQuery(document).ready(function() {
    if (location.host === "addmefast.com") {
      new Addme();
    } else if (location.host === "www.facebook.com") {
      new Facebook();
    }
    return setTimeout(function() {
      return location.reload();
    }, 1000 * 60 * 10);
  });

}).call(this);
